### ISSUE TITLE
can you do a tutorial / detailed readme on how to use the source? (i can pay for this)

### ISSUE THREAD

**Issue by Suwup** [b9q/loader_V#2]
my discord Suwup#0001

**Comment by segregator** [comment]
Recently I have a lot of spare time so I'll probably just update the read me file & include a rough sketch of the DB as I lost the original  for it

**Comment by Suwup** [comment]
> Recently I have a lot of spare time so I'll probably just update the read me file & include a rough sketch of the DB as I lost the original for it

can you add me on discord: Suwup#0001 and help me set up this? or just tell me how to set up the sql database

**Comment by henkezx** [comment]
any updates? that sql file would be nice to have ;)

**Comment by Sehyn** [comment]
Mostlikely not gonna happen
